info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T18:45:16.319Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T18:45:29.377Z"}
info: Connected to the database. {"timestamp":"2022-06-26T18:45:32.653Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T18:46:04.372Z"}
info: Connected to the database. {"timestamp":"2022-06-26T18:46:07.434Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T18:46:31.298Z"}
info: Connected to the database. {"timestamp":"2022-06-26T18:46:34.687Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T18:46:53.288Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T18:46:59.612Z"}
info: Connected to the database. {"timestamp":"2022-06-26T18:47:02.488Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:03:52.442Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:03:55.687Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:05:13.795Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:05:17.092Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:06:19.191Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:06:22.860Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:07:12.768Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:07:15.591Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:22:42.961Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:22:46.255Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:23:17.232Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:23:20.002Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:24:00.943Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:24:03.986Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:24:09.862Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:24:12.757Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:28:17.546Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:28:28.173Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:28:31.110Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:29:00.370Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:29:03.217Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:36:17.223Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:36:20.418Z"}
error: 
    status - 500 
    message - ValidationError: "fname" is required 
    url - /api/v1/users/newuser 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T19:37:59.885Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:47:15.362Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:47:18.555Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T19:58:59.404Z"}
info: Connected to the database. {"timestamp":"2022-06-26T19:59:02.615Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:19)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:00:02.951Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:02:01.755Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:02:05.028Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:02:38.233Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:02:40.985Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:03:34.018Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:03:37.395Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:04:05.214Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:04:08.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:07:51.466Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:07:54.805Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:09:17.038Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:09:20.133Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:19)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:09:25.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:10:14.916Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:10:18.048Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:19)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:10:22.091Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:11:02.363Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:11:05.254Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:12:00.935Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:12:04.049Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:12:15.763Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:12:18.753Z"}
error: 
    status - 500 
    message - undefined 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:12:22.713Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:13:13.539Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:13:16.904Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:19)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:13:22.349Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:14:17.187Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:14:20.181Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:19)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:14:29.938Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:15:03.368Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:15:06.212Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:15:44.410Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:15:47.382Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:17:20.037Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:17:23.066Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:18:04.694Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:18:07.523Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:19:45.773Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:19:48.907Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:20:12.015Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:20:14.923Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:23:44.496Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:23:47.843Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:25:37.674Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:25:41.021Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:26:10.768Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:26:13.657Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:26:24.746Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:26:27.575Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:26:47.267Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:26:50.484Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:32:30.743Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:32:33.850Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:34:27.738Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:34:31.288Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:35:16.753Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:35:19.681Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:36:12.383Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:36:15.380Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:37:21.405Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:37:24.707Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:37:32.780Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:37:40.230Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:38:08.977Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:38:11.861Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:38:23.271Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:38:26.559Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:19)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:38:29.203Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:39:47.575Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:40:17.254Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:40:20.145Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:42:21.814Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:42:24.853Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:19)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:42:30.632Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:43:23.667Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:43:31.160Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:43:33.993Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:19)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:43:46.788Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:44:07.751Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:44:10.618Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:19)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:52:54.818Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:53:37.030Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:53:40.732Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:19)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:53:45.315Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:54:38.659Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:54:42.031Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:55:05.688Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:55:08.604Z"}
error: 
    status - 500 
    message - ReferenceError: erro is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:69:7)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T20:55:13.822Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:55:36.789Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:55:39.672Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:55:59.981Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:56:02.837Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:56:16.063Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:56:23.480Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:56:26.419Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:56:52.980Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:56:56.200Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:57:20.514Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:57:23.382Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:57:34.487Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:57:37.431Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:57:56.034Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:57:59.381Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:58:29.342Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:58:32.187Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:59:02.379Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:59:05.390Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:59:14.423Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:59:17.247Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:59:25.116Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T20:59:45.743Z"}
info: Connected to the database. {"timestamp":"2022-06-26T20:59:48.755Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:00:10.721Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:00:13.951Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:00:54.571Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:01:07.151Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:01:10.097Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:02:39.144Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:02:42.245Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:03:10.507Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:03:13.378Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:03:27.388Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:03:30.328Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:04:46.806Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:04:49.941Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:05:26.995Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:05:29.844Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:05:48.700Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:05:52.026Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:06:41.253Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:06:44.096Z"}
error: 
    status - 500 
    message - ReferenceError: difError is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:7)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T21:06:46.256Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:12:39.762Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:38:09.220Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:38:12.349Z"}
error: 
    status - 500 
    message - ReferenceError: difError is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:7)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T21:42:26.767Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 41
    at JSON.parse (<anonymous>)
    at parse (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at invokeCallback (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\raw-body\index.js:231:16)
    at done (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:527:28)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T21:42:58.529Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T21:47:39.060Z"}
info: Connected to the database. {"timestamp":"2022-06-26T21:47:43.355Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:14:44.126Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:14:47.730Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:15:48.615Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:15:51.788Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'mailid')
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:62:50)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T22:16:11.955Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:16:49.232Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:16:53.384Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'status')
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:71:11)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T22:17:01.724Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:17:43.198Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:17:46.116Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:71:7)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T22:17:55.050Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:22:54.859Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:22:58.125Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:27:41.889Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:27:45.484Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:29:49.320Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:29:52.576Z"}
error: 
    status - 500 
    message - ReferenceError: test is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:16)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T22:30:02.541Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:31:23.169Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:31:26.391Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:31:43.358Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:31:46.195Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:31:57.265Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:32:00.156Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T22:32:35.319Z"}
info: Connected to the database. {"timestamp":"2022-06-26T22:32:38.569Z"}
error: 
    status - 500 
    message - ReferenceError: difError is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:7)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T22:32:41.081Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T02:43:21.189Z"}
info: Connected to the database. {"timestamp":"2022-06-27T02:43:24.525Z"}
error: 
    status - 500 
    message - ReferenceError: difError is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:70:7)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-27T02:47:19.797Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T02:50:47.054Z"}
info: Connected to the database. {"timestamp":"2022-06-27T02:50:51.592Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T02:51:15.896Z"}
info: Connected to the database. {"timestamp":"2022-06-27T02:51:18.752Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T02:51:30.827Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T02:51:51.717Z"}
info: Connected to the database. {"timestamp":"2022-06-27T02:51:54.958Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T02:58:51.586Z"}
info: Connected to the database. {"timestamp":"2022-06-27T02:58:55.118Z"}
error: 
    status - 500 
    message - Error: Mail Is not exist
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:77:11)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-27T02:59:01.803Z"}
error: 
    status - 500 
    message - Error: Mail Is not exist
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:77:11)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-27T02:59:35.206Z"}
error: 
    status - 500 
    message - Error: Password is incorrect
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:72:13)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-27T02:59:43.601Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T03:02:00.179Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T03:02:19.090Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T03:02:32.711Z"}
info: Connected to the database. {"timestamp":"2022-06-27T03:02:35.627Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T03:02:59.891Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T03:03:14.144Z"}
info: Connected to the database. {"timestamp":"2022-06-27T03:03:17.039Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T04:09:52.839Z"}
info: Connected to the database. {"timestamp":"2022-06-27T04:09:56.243Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T04:11:13.152Z"}
info: Connected to the database. {"timestamp":"2022-06-27T04:11:16.300Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T04:15:53.181Z"}
info: Connected to the database. {"timestamp":"2022-06-27T04:15:56.252Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T04:16:23.341Z"}
info: Connected to the database. {"timestamp":"2022-06-27T04:16:26.304Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T04:17:21.080Z"}
info: Connected to the database. {"timestamp":"2022-06-27T04:17:24.350Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T06:01:00.551Z"}
info: Connected to the database. {"timestamp":"2022-06-27T06:01:03.850Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T06:15:24.881Z"}
info: Connected to the database. {"timestamp":"2022-06-27T06:15:28.009Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T06:15:39.562Z"}
info: Connected to the database. {"timestamp":"2022-06-27T06:15:42.460Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-27T06:16:13.140Z"}
info: Connected to the database. {"timestamp":"2022-06-27T06:16:16.157Z"}
