info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:37:03.677Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:37:07.581Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:41:29.101Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:41:32.615Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:42:01.500Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:42:27.730Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:44:23.467Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:44:26.869Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:44:43.512Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:45:03.915Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:45:06.713Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:45:31.012Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:45:34.287Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:47:42.228Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:47:45.384Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:48:07.024Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:48:13.714Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:48:16.670Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to deleteOne() must be an object, got 62bc6ab3053164405cff5623
    at model.Query.Query.deleteOne (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\query.js:2837:16)
    at Function.deleteOne (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\model.js:2049:13)
    at _callee5$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:58:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.deleteNote (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:57:24)
    at _callee5$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/note.controller.js:73:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/note/62bc6ab3053164405cff5623 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-29T19:50:03.667Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:50:44.081Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:50:47.222Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to deleteOne() must be an object, got 62bc6ab3053164405cff5623
    at model.Query.Query.deleteOne (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\query.js:2837:16)
    at Function.deleteOne (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\model.js:2049:13)
    at _callee5$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:58:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.deleteNote (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:57:24)
    at _callee5$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/note.controller.js:73:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/note/62bc6ab3053164405cff5623 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-29T19:50:50.170Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:52:10.781Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:52:13.935Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to deleteOne() must be an object, got 62bc6ab3053164405cff5623
    at model.Query.Query.deleteOne (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\query.js:2837:16)
    at Function.deleteOne (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\model.js:2049:13)
    at _callee5$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:58:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.deleteNote (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:57:24)
    at _callee5$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/note.controller.js:73:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/note/62bc6ab3053164405cff5623 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-29T19:52:22.266Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:52:50.887Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:52:53.753Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:53:58.538Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:54:01.626Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:54:30.744Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:54:33.871Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to deleteOne() must be an object, got 62bc6ab3053164405cff5623
    at model.Query.Query.deleteOne (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\query.js:2837:16)
    at Function.deleteOne (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\model.js:2049:13)
    at _callee5$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:58:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.deleteNote (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:57:24)
    at _callee5$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/note.controller.js:73:23)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/note/62bc6ab3053164405cff5623 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-29T19:54:37.848Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:55:16.950Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:55:19.986Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to deleteOne() must be an object, got 62bc6ab3053164405cff5623
    at model.Query.Query.deleteOne (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\query.js:2837:16)
    at Function.deleteOne (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\model.js:2049:13)
    at _callee5$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:58:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.deleteNote (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:57:24)
    at _callee5$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/note.controller.js:73:23)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/note/62bc6ab3053164405cff5623 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-29T19:55:22.801Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T19:56:09.360Z"}
info: Connected to the database. {"timestamp":"2022-06-29T19:56:12.226Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "62bc660d1adab13de41e742L" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/62bc660d1adab13de41e742L 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-29T19:57:16.660Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "62bc660d1adab13de41e742" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/62bc660d1adab13de41e742 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-29T19:57:42.038Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:07:45.373Z"}
info: Connected to the database. {"timestamp":"2022-06-29T20:07:48.845Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:09:06.758Z"}
info: Connected to the database. {"timestamp":"2022-06-29T20:09:09.918Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:09:38.804Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:09:49.903Z"}
info: Connected to the database. {"timestamp":"2022-06-29T20:09:52.905Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:10:24.387Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:10:35.815Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:10:42.159Z"}
info: Connected to the database. {"timestamp":"2022-06-29T20:10:45.010Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:11:56.013Z"}
info: Connected to the database. {"timestamp":"2022-06-29T20:11:59.222Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:12:20.565Z"}
info: Connected to the database. {"timestamp":"2022-06-29T20:12:23.599Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:12:51.421Z"}
info: Connected to the database. {"timestamp":"2022-06-29T20:12:54.334Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T20:13:20.811Z"}
info: Connected to the database. {"timestamp":"2022-06-29T20:13:24.716Z"}
error: 
    status - 500 
    message - Error: Invalid ID
    at _callee4$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/note.service.js:50:13)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/62454ae713ca132de4ea41a9 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-29T20:21:45.795Z"}
